# Generated by Django 4.0.2 on 2022-02-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='courseNum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='duration',
            field=models.FloatField(),
        ),
    ]
